# Toggle the gtest harness under test/ (tester binary + poozle_unit_tests).
option('tests', type: 'feature', value: 'enabled', description: 'Build gtest suite.')
option('sanitizer', type: 'combo', choices: ['none', 'address', 'thread', 'undefined', 'address,undefined'], value: 'none', description: 'Enable compiler sanitizers.')
